LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_SRC_FILES := $(call all-subdir-java-files)

LOCAL_STATIC_JAVA_LIBRARIES := HiNetShare
LOCAL_STATIC_JAVA_LIBRARIES += HiBDInfo
#LOCAL_STATIC_JAVA_LIBRARIES += SDKInvoke
LOCAL_STATIC_JAVA_LIBRARIES += HiDVDInfo
#LOCAL_STATIC_JAVA_LIBRARIES += HiSysManager

LOCAL_PACKAGE_NAME := HiVideoCenter
ALL_DEFAULT_INSTALLED_MODULES += $(LOCAL_PACKAGE_NAME)

include $(CLEAR_VARS) 
LOCAL_MODULE := libbdinfo_jni  
LOCAL_SRC_FILES := libbdinfo_jni.so  
include $(PREBUILT_SHARED_LIBRARY)  



LOCAL_CERTIFICATE := platform

LOCAL_PROGUARD_ENABLED := disabled

include $(BUILD_PACKAGE)
